services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: collaborativecode
    volumes:
      - mysql:/data/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql


networks:
  mysql:
    driver: bridge

volumes:
  mysql: